//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autumn.Mvc.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autumn.Mvc.Infrastructure.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;lKdHGicZnSE+8QOrCRxd2v2wTE0Kjdu5ur7kziv5SFVDe30O41ysr9exxws1VszFxwQNwvJYWp5JV0kJhWpycxiAqMYhZFyYy1Jk0pWJvCly6vic6IZNzm7Vgo4izu9kN1RcS9CgoOUTmCe1hjJz82XqkT36EUDn8Ssi6AfDS80=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;0C4fajhXEzO+gqkt7TJWbqJCIlP4CTMz5i/l4EKwz+7JmB0Mhbu5dUimSYylci6KEwp7XK9cH22+Cxzzn1cWTw==&lt;/P&gt;&lt;Q&gt;tsy67q0EAwSM2eDO7nA2k2Mw7L+a8NXzrt/M0avGSMqZJ4sJ49PXDodSFryZX44MN3/t6xORZaHy6Bsk66ARIw==&lt;/Q&gt;&lt;DP&gt;XS1XqD5BUvnk+ixovvK51tjPCvhUWyHMx+mGVSLkapzxJCFUWoMUVhdHPkIyRvHnoPAfGPPwIq0G04iIzje3Zw==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RSAPrivateKey {
            get {
                return ResourceManager.GetString("RSAPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;lKdHGicZnSE+8QOrCRxd2v2wTE0Kjdu5ur7kziv5SFVDe30O41ysr9exxws1VszFxwQNwvJYWp5JV0kJhWpycxiAqMYhZFyYy1Jk0pWJvCly6vic6IZNzm7Vgo4izu9kN1RcS9CgoOUTmCe1hjJz82XqkT36EUDn8Ssi6AfDS80=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string RSAPublicKey {
            get {
                return ResourceManager.GetString("RSAPublicKey", resourceCulture);
            }
        }
    }
}
